version: "3"
services:
  api_rest:
    image: mhart/alpine-node:8
    container_name: twentty_rest
    restart: on-failure
    working_dir: /twentty
    command: npm start
    ports:
     - "3000:3000"
    volumes:
     - ./backend/rest:/twentty
    depends_on:
     - mongo
    networks:
     - twentty_net
  api_graphql:
    image: mhart/alpine-node:8
    container_name: twentty_graphql
    restart: on-failure
    working_dir: /twentty
    command: npm start
    ports:
     - "3001:3001"
    volumes:
     - ./backend/graphql:/twentty
    depends_on:
     - 'mongo'
    networks:
     - twentty_net
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo_twentty
    ports:
     - "27018:27017"
    volumes:
     - /data/db
    networks:
     - twentty_net
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_twentty
    ports:
    - "9090:9090"
    volumes:
      - ./backend/prometheus/:/etc/prometheus
    depends_on:
      - api_rest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - twentty_net
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana_twentty
    environment:
     - GF_DISABLE_LOGIN_FORM=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1
    volumes:
     - myGrafanaVol:/var/lib/grafana
     - ./backend/grafana/:/etc/grafana/provisioning/datasources/
    ports:
     - "3500:3000"
    depends_on:
     - prometheus 
    networks:
     - twentty_net
volumes:
  myGrafanaVol:
networks:
  twentty_net: